name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Linting
        run: yarn lint
      - name: Build frontend
        run: yarn build
      - name: Deploy frontend
        uses: ..... (deployment action for frontend)

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Linting
        run: yarn lint
      - name: Build backend
        run: yarn build
      - name: Deploy backend
        uses: ..... (deployment action for backend)
